import { useEffect, useMemo, useRef, useState, type PointerEvent, type ReactNode } from 'react';
import { getBudgetEstimate, getLatestActual, getExecutionRate, getMetricProvenance, getMonthlyProgression, type MetricId } from '@/data/selectors';
import { getMetricDefinition } from '@/data/metricDefinitions';
import { formatCurrency, formatPercentage } from '@/lib/formatting';
import type { FinancialObservation } from '@/types/financial';
import ExplainTerm from '@/components/finance/ExplainTerm';
import FiscalYearTrace from '@/components/finance/FiscalYearTrace';
import EditorialSectionHeader from '@/components/finance/EditorialSectionHeader';
import { useInViewOnce } from '@/hooks/useInViewOnce';
import styles from './HomePage.module.css';

const METRICS: MetricId[] = ['total_expenditure', 'revenue_expenditure', 'capital_expenditure', 'revenue_receipts', 'tax_revenue_net', 'non_tax_revenue', 'non_debt_capital_receipts', 'total_receipts', 'interest_payments', 'fiscal_deficit'];
const PERIOD_LABELS: Record<string, string> = { apr: 'Apr', 'apr-may': 'May', 'apr-jun': 'Jun' };

export default function HomePage() {
  const [selectedMetric, setSelectedMetric] = useState<MetricId>('total_expenditure');
  const [provenance, setProvenance] = useState<FinancialObservation | null>(null);
  const heroRef = useRef<HTMLElement>(null);
  const selected = useMemo(() => getMetricView(selectedMetric), [selectedMetric]);
  const total = getBudgetEstimate('total_expenditure');
  const handleHeroPointerMove = (event: PointerEvent<HTMLElement>) => { if (event.pointerType === 'touch' || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const rect = event.currentTarget.getBoundingClientRect(); event.currentTarget.style.setProperty('--pointer-x', `${((event.clientX - rect.left) / rect.width) * 100}%`); event.currentTarget.style.setProperty('--pointer-y', `${((event.clientY - rect.top) / rect.height) * 100}%`); };
  return <div className={styles.page}>
    <section ref={heroRef} className={styles.hero} aria-labelledby="hero-title" onPointerMove={handleHeroPointerMove} onPointerLeave={() => { heroRef.current?.style.setProperty('--pointer-x', '50%'); heroRef.current?.style.setProperty('--pointer-y', '40%'); }}><div className={styles.heroGrid} aria-hidden="true" /><div className={styles.heroInner}><div className={styles.eyebrow}><span className={styles.liveDot} /> India · Union Government · FY 2026–27</div><p className={styles.heroOverline}>The year ahead, measured against the year underway</p><div className={styles.heroFigure}><span className={styles.heroCurrency}>₹</span><AnimatedHeroValue value={total?.amount ?? null} /><span className={styles.heroUnit}>lakh<br />crore</span></div><h1 id="hero-title">Planned expenditure.<br /><em>Seen in motion.</em></h1><p className={styles.heroIntro}>A living view of India’s public finances — from the Budget Estimate to the first recorded quarter.</p><StatusPill /><div className={styles.heroTrace}><div className={styles.traceLabel}><span>FISCAL-YEAR TRACE</span><span>APR 2026 — MAR 2027</span></div><FiscalYearTrace /></div></div><div className={styles.heroFoot}><span>01 / 06</span><span>Scroll to explore <span className={styles.arrow}>↓</span></span></div></section>
    <section className={styles.realitySection} aria-labelledby="reality-title"><SectionRail number="01" label="Budget → Reality" /><div className={styles.sectionIntro}><p className={styles.kicker}>A quarter in focus</p><h2 id="reality-title">The Budget is a plan.<br /><span>Reality arrives cumulatively.</span></h2><p>Every figure below keeps its accounting meaning intact: an annual Budget Estimate beside provisional actuals recorded from April through June 2026.</p></div><div className={styles.realityLayout}><div className={styles.metricPicker} role="tablist" aria-label="Select a fiscal metric">{METRICS.map(id => <button key={id} role="tab" aria-selected={selectedMetric === id} className={selectedMetric === id ? styles.metricTabActive : styles.metricTab} onClick={() => setSelectedMetric(id)}>{getMetricDefinition(id)?.displayName.replace(' (Net to Centre)', '')}</button>)}</div><BudgetRealityChart view={selected} /></div><div className={styles.realityDetails}><Detail label="Budget Estimate" value={selected.be ? formatCurrency(selected.be.amount) : 'Data unavailable'} note="planned annual value" /><Detail label="Actual through June" value={selected.actual ? formatCurrency(selected.actual.amount) : 'Data unavailable'} note="cumulative provisional" /><Detail label="Execution" value={<AnimatedPercent value={selected.rate?.value ?? null} />} note={selected.rate ? 'of annual Budget Estimate recorded' : 'not calculated'} /><button className={styles.sourceButton} onClick={() => setProvenance(selected.actual ?? selected.be)} aria-label={`View source for ${selected.name}`}><span>↗</span> View source</button></div><p className={styles.neutralNote}>A lower or higher first-quarter share is not, by itself, a performance judgment. Government spending and receipts do not arrive evenly across the year.</p></section>
    <section className={styles.splitSection} aria-labelledby="split-title"><SectionRail number="02" label="Composition" /><div className={styles.splitCopy}><p className={styles.kicker}>Two kinds of spending</p><h2 id="split-title">What kind of<br /><span>expenditure is this?</span></h2><p>Revenue expenditure keeps the government running. Capital expenditure is associated with creating assets, investing, or reducing liabilities. Both are part of the public-finance story.</p></div><div className={styles.compareVisual}><CompareBar label="Revenue expenditure" id="revenue_expenditure" tone="warm" onSource={setProvenance} /><CompareBar label="Capital expenditure" id="capital_expenditure" tone="cool" onSource={setProvenance} /></div></section>
    <section className={styles.flowSection} aria-labelledby="flow-title"><SectionRail number="03" label="Where money comes from" /><div className={styles.flowHeader}><div><p className={styles.kicker}>₹100 mode · Budget Estimate</p><h2 id="flow-title">For every ₹100<br /><span>the Union expects to receive…</span></h2></div><p className={styles.flowIntro}>A complete, additive composition of non-borrowed receipts. Borrowing is deliberately outside this ₹100.</p></div><div className={styles.flowChart}><div className={styles.donut} role="img" aria-label="₹100 composition: 80.5 rupees tax revenue, 16.1 rupees non-tax revenue, and 3.4 rupees non-debt capital receipts" style={{ background: `linear-gradient(90deg, #b29054 0 ${receiptShare('tax_revenue_net')}%, #87958e ${receiptShare('tax_revenue_net')}% ${Number(receiptShare('tax_revenue_net')) + Number(receiptShare('non_tax_revenue'))}%, #c9c0aa ${Number(receiptShare('tax_revenue_net')) + Number(receiptShare('non_tax_revenue'))}% 100%)` }}><div><strong>₹100</strong><span>non-borrowed receipts</span></div></div><div className={styles.flowLegend}><FlowLine label="Tax revenue" id="tax_revenue_net" /><FlowLine label="Non-tax revenue" id="non_tax_revenue" /><FlowLine label="Non-debt capital receipts" id="non_debt_capital_receipts" /></div></div><p className={styles.sourceLine}>Composition uses Revenue Receipts + Non-Debt Capital Receipts = Total Receipts. <button onClick={() => setProvenance(getBudgetEstimate('total_receipts'))}>Source details ↗</button></p></section>
    <section className={styles.deficitSection} aria-labelledby="deficit-title"><SectionRail number="04" label="Fiscal deficit" /><div className={styles.deficitLayout}><div><p className={styles.kicker}>The gap that needs financing</p><h2 id="deficit-title">Not a mystery.<br /><span>A measurable gap.</span></h2><p>Fiscal deficit represents the gap between total expenditure and receipts excluding borrowings and certain financing items, according to the applicable government accounting definition.</p><ExplainTerm term="Fiscal deficit" /></div><div className={styles.deficitFigure}><span>Budget Estimate</span><strong>{formatObservation(getBudgetEstimate('fiscal_deficit'))}</strong><small>Actual through June: {formatObservation(getLatestActual('fiscal_deficit'))} · {getExecutionRate('fiscal_deficit') ? formatPercentage(getExecutionRate('fiscal_deficit')!.value) : 'Data unavailable'}</small><div className={styles.deficitLine}><i style={{ width: `${Math.min(getExecutionRate('fiscal_deficit')?.value ?? 0, 100)}%` }} /></div><button onClick={() => setProvenance(getLatestActual('fiscal_deficit'))}>Inspect provenance ↗</button></div></div></section>
    <section className={styles.explorerSection} aria-labelledby="explore-title"><SectionRail number="05" label="Explore the numbers" /><div className={styles.explorerHeader}><div><p className={styles.kicker}>The full picture</p><h2 id="explore-title">One dataset.<br /><span>Ten ways to read it.</span></h2></div><p>Choose a metric to see its exact value, its place in the year, and the source behind it.</p></div><div className={styles.explorerPanel}><div className={styles.explorerSelect}><label htmlFor="metric-select">Metric</label><select id="metric-select" value={selectedMetric} onChange={e => setSelectedMetric(e.target.value as MetricId)}>{METRICS.map(id => <option key={id} value={id}>{getMetricDefinition(id)?.displayName}</option>)}</select><p>{selected.definition}</p></div><Progression view={selected} onSource={setProvenance} /></div></section>
    <section className={styles.methodSection} aria-labelledby="method-title"><SectionRail number="06" label="Trust, by design" /><div className={styles.methodGrid}><div><p className={styles.kicker}>Methodology</p><h2 id="method-title">Numbers with<br /><span>their receipts.</span></h2></div><div><p>Arthrekha connects the Union Budget 2026–27 Budget Estimates from the Ministry of Finance with provisional cumulative actuals from the Controller General of Accounts.</p><div className={styles.methodMeta}><span>DATA THROUGH<br /><strong>JUNE 2026</strong></span><span>STATUS<br /><strong>PROVISIONAL / UNAUDITED</strong></span><span>OBSERVATIONS<br /><strong>40 NORMALIZED</strong></span></div></div></div></section>
    {provenance && <ProvenanceDrawer observation={provenance} onClose={() => setProvenance(null)} />}
  </div>;
}

function getMetricView(id: MetricId) { const def = getMetricDefinition(id); return { id, name: def?.displayName ?? id, definition: def?.longDescription ?? 'Definition unavailable.', be: getBudgetEstimate(id), actual: getLatestActual(id), rate: getExecutionRate(id), progression: getMonthlyProgression(id) }; }
type MetricView = ReturnType<typeof getMetricView>;
function Detail({ label, value, note }: { label: string; value: ReactNode; note: string }) { return <div><span className={styles.detailLabel}>{label}</span><strong>{value}</strong><small>{note}</small></div>; }
function useAnimatedValue(value: number | null) { const initial = value === null ? null : (window.matchMedia('(prefers-reduced-motion: reduce)').matches ? value : 0); const [display, setDisplay] = useState<number | null>(initial); const previous = useRef<number | null>(initial); useEffect(() => { if (value === null || previous.current === value || window.matchMedia('(prefers-reduced-motion: reduce)').matches) { setDisplay(value); previous.current = value; return; } const from = previous.current ?? 0; const started = performance.now(); let frame = 0; const tick = (now: number) => { const progress = Math.min((now - started) / 780, 1); const eased = 1 - Math.pow(1 - progress, 3); setDisplay(from + (value - from) * eased); if (progress < 1) frame = requestAnimationFrame(tick); else previous.current = value; }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [value]); return display; }
function AnimatedCurrency({ value }: { value: number | null }) { const animated = useAnimatedValue(value); return <strong className={styles.animatedCurrency}>{animated === null ? 'Data unavailable' : formatCurrency(animated)}</strong>; }
function AnimatedPercent({ value }: { value: number | null }) { const animated = useAnimatedValue(value); return <>{animated === null ? 'Data unavailable' : formatPercentage(animated)}</>; }
function AnimatedHeroValue({ value }: { value: number | null }) { const animated = useAnimatedValue(value); return <span className={styles.heroValue}>{animated === null ? '—' : (animated / 100000).toFixed(1)}</span>; }
function SectionRail({ number, label }: { number: string; label: string }) { return <div className={styles.sectionRail}><EditorialSectionHeader index={number} title={label} /></div>; }
function BudgetRealityChart({ view }: { view: MetricView }) { const be = view.be?.amount ?? null; const actual = view.actual?.amount ?? null; const width = be && actual ? actual / be * 100 : 0; const { ref, hasEntered } = useInViewOnce<HTMLDivElement>(); return <div ref={ref} className={`${styles.chartStage} ${hasEntered ? styles.chartRevealed : ''}`}><div className={styles.chartTitle}><span>{view.name}</span><span className={styles.chartStatus}>PLAN / EXECUTION</span></div><div className={styles.instrument} aria-label={`${view.name}: annual Budget Estimate and provisional actual through June`}><div className={styles.instrumentRow}><div className={styles.instrumentLabel}><span className={styles.planKey} /><div><strong>Budget Estimate</strong><small>annual plan</small></div></div><div className={styles.instrumentTrack}><span className={styles.trackEnd} /><div className={styles.planLine} /></div><AnimatedCurrency value={be} /></div><div className={styles.instrumentRow}><div className={styles.instrumentLabel}><span className={styles.actualKey} /><div><strong>Actual through June</strong><small>cumulative · provisional</small></div></div><div className={styles.instrumentTrack}><span className={styles.trackEnd} /><div className={styles.actualLine} style={{ width: hasEntered ? `${width}%` : '0%' }}><i /></div><b className={styles.actualPoint} style={{ left: hasEntered ? `${width}%` : '0%' }} /></div><AnimatedCurrency value={actual} /></div></div><div className={styles.instrumentAxis}><span>0</span><span>100% of annual Budget Estimate</span></div><p className={styles.chartCaption}>{view.actual ? `${formatPercentage(view.rate?.value ?? 0)} of the annual Budget Estimate had been recorded through June.` : 'Actual data is unavailable for this metric.'}</p></div>; }
function CompareBar({ label, id, tone, onSource }: { label: string; id: MetricId; tone: 'warm' | 'cool'; onSource: (o: FinancialObservation | null) => void }) { const be = getBudgetEstimate(id); const actual = getLatestActual(id); const rate = getExecutionRate(id); return <div className={styles.compareRow}><div className={styles.compareLabel}><span className={tone === 'warm' ? styles.warmMark : styles.coolMark} /><div><strong>{label}</strong><small>{rate ? formatPercentage(rate.value) : 'Data unavailable'} through June</small></div></div><div className={styles.compareValues}><span><small>BE</small>{be ? formatCurrency(be.amount) : 'Data unavailable'}</span><span><small>ACTUAL</small>{actual ? formatCurrency(actual.amount) : 'Data unavailable'}</span><button onClick={() => onSource(actual ?? be)} aria-label={`View source for ${label}`}>↗</button></div><div className={styles.compareTrack}><i className={tone === 'warm' ? styles.warmBar : styles.coolBar} style={{ width: `${Math.min(rate?.value ?? 0, 100)}%` }} /></div></div>; }
function FlowLine({ label, id }: { label: string; id: MetricId }) { const value = getBudgetEstimate(id)?.amount ?? 0; const total = getBudgetEstimate('total_receipts')?.amount ?? 1; const share = value / total * 100; return <div className={styles.flowLine}><span>{label}</span><strong>{share.toFixed(1)}%</strong><small>{formatCurrency(value)}</small><i><b style={{ width: `${share}%` }} /></i></div>; }
function receiptShare(id: MetricId) { const value = getBudgetEstimate(id)?.amount ?? 0; const total = getBudgetEstimate('total_receipts')?.amount ?? 1; return (value / total * 100).toFixed(1); }
function StatusPill() { return <div className={styles.statusPill}><span>PROVISIONAL</span><b>Actual data through June 2026</b><small>Subject to audit by CAG</small></div>; }
function formatObservation(observation: FinancialObservation | null) { return observation ? formatCurrency(observation.amount) : 'Data unavailable'; }
function Progression({ view, onSource }: { view: MetricView; onSource: (o: FinancialObservation | null) => void }) { const points = view.progression; const periodIndex: Record<string, number> = { apr: 0, 'apr-may': 1, 'apr-jun': 2 }; return <div className={styles.progression}><div className={styles.progressionHead}><span>YTD progression</span><button onClick={() => onSource(view.actual ?? view.be)}>Source ↗</button></div>{points.length ? <div className={styles.progressionTrace} role="img" aria-label={`${view.name} cumulative progression: ${points.map(p => `${PERIOD_LABELS[p.period ?? '']}: ${formatCurrency(p.amount)}`).join(', ')}. July through March are not available.`}><div className={styles.progressionLine}><i style={{ width: `${((periodIndex[points[points.length - 1]?.period ?? 'apr-jun'] ?? 2) / 11) * 100}%` }} /></div>{['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'].map((month, index) => { const point = points.find(p => periodIndex[p.period ?? ''] === index); return <div className={`${styles.progressionPoint} ${point ? styles.progressionPointComplete : styles.progressionPointFuture}`} key={month}><b>{point ? '●' : '○'}</b><strong>{month}</strong>{point && <span>{formatCurrency(point.amount)}</span>}</div>; })}</div> : <p>Progression unavailable for this metric.</p>}<small>Each point is cumulative YTD; no monthly flow has been inferred. Future periods are not available.</small></div>; }
function EvidenceTrace({ observation }: { observation: FinancialObservation }) { const derived = observation.estimateType !== 'BE' ? getExecutionRate(observation.metric) : null; return <div className={styles.evidenceTrace}><div><b>01</b><span>Source value</span><small>{observation.source.organization}</small></div><i /> <div><b>02</b><span>Normalized observation</span><small>Arthrekha dataset · ₹ crore</small></div>{derived && <><i /><div><b>03</b><span>Derived calculation</span><small>Actual YTD ÷ BE × 100</small></div></>}</div>; }
function ProvenanceDrawer({ observation, onClose }: { observation: FinancialObservation; onClose: () => void }) { const provenance = getMetricProvenance(observation); const def = getMetricDefinition(observation.metric); return <div className={styles.drawerBackdrop} onClick={onClose}><aside className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="provenance-title" onClick={e => e.stopPropagation()}><button className={styles.closeButton} onClick={onClose} aria-label="Close source details">×</button><p className={styles.kicker}>Provenance</p><h2 id="provenance-title">{def?.displayName ?? observation.metric}</h2><div className={styles.provenanceStatus}>{observation.estimateType === 'BE' ? 'BUDGET ESTIMATE' : 'PROVISIONAL ACTUAL'}<span>{observation.estimateType === 'BE' ? 'Annual plan' : 'Cumulative through June 2026'}</span></div><dl>{provenance && <><dt>Jurisdiction</dt><dd>Union Government of India</dd><dt>Financial year</dt><dd>FY {observation.financialYear}</dd><dt>Period</dt><dd>{observation.estimateType === 'BE' ? 'Full year' : 'April–June 2026 (YTD)'}</dd><dt>Source organization</dt><dd>{provenance.source.organization}</dd><dt>Source document</dt><dd>{provenance.source.document}</dd><dt>Published</dt><dd>{provenance.source.publishedAt ?? 'Not available'}</dd><dt>Retrieved</dt><dd>{provenance.source.retrievedAt}</dd><dt>Data status</dt><dd>{provenance.source.dataStatus === 'provisional' ? 'Provisional / unaudited' : 'Final Budget Estimate'}</dd></>}</dl><EvidenceTrace observation={observation} /><p className={styles.drawerNote}>Source value shown directly from the normalized observation. Derived execution rates are calculated separately as Actual YTD ÷ Budget Estimate × 100.</p>{provenance?.source.url && <a href={provenance.source.url} target="_blank" rel="noreferrer">Open source publication ↗</a>}</aside></div>; }
