import { useEffect, useMemo, useRef, useState, type PointerEvent, type ReactNode } from 'react';
import { getBudgetEstimate, getLatestActual, getExecutionRate, getMetricProvenance, getMonthlyProgression, getDatasetMetadata, type MetricId } from '@/data/selectors';
import { getMetricDefinition } from '@/data/metricDefinitions';
import { formatCurrency, formatPercentage } from '@/lib/formatting';
import type { FinancialObservation } from '@/types/financial';
import ExplainTerm from '@/components/finance/ExplainTerm';
import FiscalYearTrace from '@/components/finance/FiscalYearTrace';
import EditorialSectionHeader from '@/components/finance/EditorialSectionHeader';
import { useInViewOnce } from '@/hooks/useInViewOnce';
import styles from './HomePage.module.css';
import { useTranslation } from '@/i18n';

const METRICS: MetricId[] = ['total_expenditure', 'revenue_expenditure', 'capital_expenditure', 'revenue_receipts', 'tax_revenue_net', 'non_tax_revenue', 'non_debt_capital_receipts', 'non_borrowed_receipts', 'interest_payments', 'fiscal_deficit'];
const PERIOD_LABELS: Record<string, string> = { apr: 'Apr', 'apr-may': 'May', 'apr-jun': 'Jun' };

export default function HomePage() {
  const { t, localizeFormattedValue, localizeMetric } = useTranslation();
  const [selectedMetric, setSelectedMetric] = useState<MetricId>('total_expenditure');
  const [provenance, setProvenance] = useState<FinancialObservation | null>(null);
  const heroRef = useRef<HTMLElement>(null);
  const selected = useMemo(() => getMetricView(selectedMetric, localizeMetric, t), [selectedMetric, localizeMetric, t]);
  const total = getBudgetEstimate('total_expenditure');
  const handleHeroPointerMove = (event: PointerEvent<HTMLElement>) => { if (event.pointerType === 'touch' || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const rect = event.currentTarget.getBoundingClientRect(); event.currentTarget.style.setProperty('--pointer-x', `${((event.clientX - rect.left) / rect.width) * 100}%`); event.currentTarget.style.setProperty('--pointer-y', `${((event.clientY - rect.top) / rect.height) * 100}%`); };
  return <div className={styles.page}>
    <section ref={heroRef} className={styles.hero} aria-labelledby="hero-title" onPointerMove={handleHeroPointerMove} onPointerLeave={() => { heroRef.current?.style.setProperty('--pointer-x', '50%'); heroRef.current?.style.setProperty('--pointer-y', '40%'); }}><div className={styles.heroGrid} aria-hidden="true" /><div className={styles.heroInner}><div className={styles.eyebrow}><span className={styles.liveDot} /> {t('India · Union Government · FY 2026–27')}</div><p className={styles.heroOverline}>{t('The year ahead, measured against the year underway')}</p><div className={styles.heroFigure}><span className={styles.heroCurrency}>₹</span><AnimatedHeroValue value={total?.amount ?? null} /><span className={styles.heroUnit}>{t('lakh')}<br />{t('crore')}</span></div><h1 id="hero-title">{t('Planned expenditure.')}<br /><em>{t('Seen in motion.')}</em></h1><p className={styles.heroIntro}>{t('A living view of India’s public finances — from the Budget Estimate to the first recorded quarter.')}</p><StatusPill /><div className={styles.heroTrace}><div className={styles.traceLabel}><span>{t('FISCAL-YEAR TRACE')}</span><span>{t('APR 2026 — MAR 2027')}</span></div><FiscalYearTrace /></div></div><div className={styles.heroFoot}><span>01 / 06</span><span>{t('Scroll to explore')} <span className={styles.arrow}>↓</span></span></div></section>
    <section className={styles.realitySection} aria-labelledby="reality-title"><SectionRail number="01" label={t('Budget → Reality')} /><div className={styles.sectionIntro}><p className={styles.kicker}>{t('A quarter in focus')}</p><h2 id="reality-title">{t('The Budget is a plan.')}<br /><span>{t('Reality arrives cumulatively.')}</span></h2><p>{t('Every figure below keeps its accounting meaning intact: an annual Budget Estimate beside provisional actuals recorded from April through June 2026.')}</p></div><div className={styles.realityLayout}><div className={styles.metricPicker} role="tablist" aria-label={t('Select a fiscal metric')}>{METRICS.map(id => { const definition = getMetricDefinition(id); return <button key={id} role="tab" aria-selected={selectedMetric === id} className={selectedMetric === id ? styles.metricTabActive : styles.metricTab} onClick={() => setSelectedMetric(id)}>{definition ? localizeMetric(definition).displayName.replace(' (Net to Centre)', '') : id}</button>; })}</div><BudgetRealityChart view={selected} /></div><div className={styles.realityDetails}><Detail label={t('Budget Estimate')} value={selected.be ? localizeFormattedValue(formatCurrency(selected.be.amount)) : t('Data unavailable')} note={t('planned annual value')} /><Detail label={t('Actual through June')} value={selected.actual ? localizeFormattedValue(formatCurrency(selected.actual.amount)) : t('Data unavailable')} note={t('cumulative provisional')} /><Detail label={t('Execution')} value={<AnimatedPercent value={selected.rate?.value ?? null} />} note={selected.rate ? t('of annual Budget Estimate recorded') : t('not calculated')} /><button className={styles.sourceButton} onClick={() => setProvenance(selected.actual ?? selected.be)} aria-label={`${t('View source for')} ${selected.name}`}><span>↗</span> {t('View source')}</button></div><p className={styles.neutralNote}>{t('A lower or higher first-quarter share is not, by itself, a performance judgment. Government spending and receipts do not arrive evenly across the year.')}</p></section>
    <section className={styles.splitSection} aria-labelledby="split-title"><SectionRail number="02" label={t('Composition')} /><div className={styles.splitCopy}><p className={styles.kicker}>{t('Two kinds of spending')}</p><h2 id="split-title">{t('What kind of')}<br /><span>{t('expenditure is this?')}</span></h2><p>{t('Revenue expenditure keeps the government running. Capital expenditure is associated with creating assets, investing, or reducing liabilities. Both are part of the public-finance story.')}</p></div><div className={styles.compareVisual}><CompareBar label={t('Revenue expenditure')} id="revenue_expenditure" tone="warm" onSource={setProvenance} /><CompareBar label={t('Capital expenditure')} id="capital_expenditure" tone="cool" onSource={setProvenance} /></div></section>
    <section className={styles.flowSection} aria-labelledby="flow-title"><SectionRail number="03" label={t('Where money comes from')} /><div className={styles.flowHeader}><div><p className={styles.kicker}>{t('₹100 mode · Budget Estimate')}</p><h2 id="flow-title">{t('For every ₹100')}<br /><span>{t('the Union expects to receive…')}</span></h2></div><p className={styles.flowIntro}>{t('A complete, additive composition of non-borrowed receipts. Borrowing is deliberately outside this ₹100.')}</p></div><div className={styles.flowChart}><div className={styles.donut} role="img" aria-label={t('₹100 composition of non-borrowed receipts')} style={{ background: `linear-gradient(90deg, #b29054 0 ${receiptShare('tax_revenue_net')}%, #87958e ${receiptShare('tax_revenue_net')}% ${Number(receiptShare('tax_revenue_net')) + Number(receiptShare('non_tax_revenue'))}%, #c9c0aa ${Number(receiptShare('tax_revenue_net')) + Number(receiptShare('non_tax_revenue'))}% 100%)` }}><div><strong>₹100</strong><span>{t('non-borrowed receipts')}</span></div></div><div className={styles.flowLegend}><FlowLine label={t('Tax revenue')} id="tax_revenue_net" /><FlowLine label={t('Non-tax revenue')} id="non_tax_revenue" /><FlowLine label={t('Non-debt capital receipts')} id="non_debt_capital_receipts" /></div></div><p className={styles.sourceLine}>{t('Composition uses Revenue Receipts + Non-Debt Capital Receipts = Non-Borrowed Receipts.')} <button onClick={() => setProvenance(getBudgetEstimate('non_borrowed_receipts'))}>{t('Source details ↗')}</button></p></section>
    <section className={styles.deficitSection} aria-labelledby="deficit-title"><SectionRail number="04" label={t('Fiscal deficit')} /><div className={styles.deficitLayout}><div><p className={styles.kicker}>{t('The gap that needs financing')}</p><h2 id="deficit-title">{t('Not a mystery.')}<br /><span>{t('A measurable gap.')}</span></h2><p>{t('Fiscal deficit represents the gap between total expenditure and receipts excluding borrowings and certain financing items, according to the applicable government accounting definition.')}</p><ExplainTerm term="Fiscal deficit" /></div><div className={styles.deficitFigure}><span>{t('Budget Estimate')}</span><strong>{formatObservation(getBudgetEstimate('fiscal_deficit'), t, localizeFormattedValue)}</strong><small>{t('Actual through June')}: {formatObservation(getLatestActual('fiscal_deficit'), t, localizeFormattedValue)} · {getExecutionRate('fiscal_deficit') ? localizeFormattedValue(formatPercentage(getExecutionRate('fiscal_deficit')!.value)) : t('Data unavailable')}</small><div className={styles.deficitLine}><i style={{ width: `${Math.min(getExecutionRate('fiscal_deficit')?.value ?? 0, 100)}%` }} /></div><button onClick={() => setProvenance(getLatestActual('fiscal_deficit'))}>{t('Inspect provenance ↗')}</button></div></div></section>
    <section className={styles.explorerSection} aria-labelledby="explore-title"><SectionRail number="05" label={t('Explore the numbers')} /><div className={styles.explorerHeader}><div><p className={styles.kicker}>{t('The full picture')}</p><h2 id="explore-title">{t('One dataset.')}<br /><span>{t('Ten ways to read it.')}</span></h2></div><p>{t('Choose a metric to see its exact value, its place in the year, and the source behind it.')}</p></div><div className={styles.explorerPanel}><div className={styles.explorerSelect}><label htmlFor="metric-select">{t('Metric')}</label><select id="metric-select" value={selectedMetric} onChange={e => setSelectedMetric(e.target.value as MetricId)}>{METRICS.map(id => { const definition = getMetricDefinition(id); return <option key={id} value={id}>{definition ? localizeMetric(definition).displayName : id}</option>; })}</select><p>{selected.definition}</p></div><Progression view={selected} onSource={setProvenance} /></div></section>
    <section className={styles.methodSection} aria-labelledby="method-title"><SectionRail number="06" label={t('Trust, by design')} /><div className={styles.methodGrid}><div><p className={styles.kicker}>{t('Methodology')}</p><h2 id="method-title">{t('Numbers with')}<br /><span>{t('their receipts.')}</span></h2></div><div><p>{t('Arthrekha connects the Union Budget 2026–27 Budget Estimates from the Ministry of Finance with provisional cumulative actuals from the Controller General of Accounts.')}</p><div className={styles.methodMeta}><span>{t('DATA THROUGH')}<br /><strong>{t('JUNE 2026')}</strong></span><span>{t('STATUS')}<br /><strong>{t('PROVISIONAL / UNAUDITED')}</strong></span><span>{t('OBSERVATIONS')}<br /><strong>{localizeFormattedValue(String(getDatasetMetadata().totalObservations))} {t('NORMALIZED')}</strong></span></div></div></div></section>
    {provenance && <ProvenanceDrawer observation={provenance} onClose={() => setProvenance(null)} />}
  </div>;
}

function getMetricView(id: MetricId, localizeMetric: ReturnType<typeof useTranslation>['localizeMetric'], t: (text: string) => string) { const rawDefinition = getMetricDefinition(id); const def = rawDefinition ? localizeMetric(rawDefinition) : null; return { id, name: def?.displayName ?? id, definition: def?.longDescription ?? t('Definition unavailable.'), be: getBudgetEstimate(id), actual: getLatestActual(id), rate: getExecutionRate(id), progression: getMonthlyProgression(id) }; }
type MetricView = ReturnType<typeof getMetricView>;
function Detail({ label, value, note }: { label: string; value: ReactNode; note: string }) { return <div><span className={styles.detailLabel}>{label}</span><strong>{value}</strong><small>{note}</small></div>; }
function useAnimatedValue(value: number | null) { const initial = value === null ? null : (window.matchMedia('(prefers-reduced-motion: reduce)').matches ? value : 0); const [display, setDisplay] = useState<number | null>(initial); const previous = useRef<number | null>(initial); useEffect(() => { if (value === null || previous.current === value || window.matchMedia('(prefers-reduced-motion: reduce)').matches) { setDisplay(value); previous.current = value; return; } const from = previous.current ?? 0; const started = performance.now(); let frame = 0; const tick = (now: number) => { const progress = Math.min((now - started) / 780, 1); const eased = 1 - Math.pow(1 - progress, 3); setDisplay(from + (value - from) * eased); if (progress < 1) frame = requestAnimationFrame(tick); else previous.current = value; }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [value]); return display; }
function AnimatedCurrency({ value }: { value: number | null }) { const { t, localizeFormattedValue } = useTranslation(); const animated = useAnimatedValue(value); return <strong className={styles.animatedCurrency}>{animated === null ? t('Data unavailable') : localizeFormattedValue(formatCurrency(animated))}</strong>; }
function AnimatedPercent({ value }: { value: number | null }) { const { t, localizeFormattedValue } = useTranslation(); const animated = useAnimatedValue(value); return <>{animated === null ? t('Data unavailable') : localizeFormattedValue(formatPercentage(animated))}</>; }
function AnimatedHeroValue({ value }: { value: number | null }) { const { localizeFormattedValue } = useTranslation(); const animated = useAnimatedValue(value); return <span className={styles.heroValue}>{animated === null ? '—' : localizeFormattedValue((animated / 100000).toFixed(1))}</span>; }
function SectionRail({ number, label }: { number: string; label: string }) { return <div className={styles.sectionRail}><EditorialSectionHeader index={number} title={label} /></div>; }
function BudgetRealityChart({ view }: { view: MetricView }) { const { t, localizeFormattedValue } = useTranslation(); const be = view.be?.amount ?? null; const actual = view.actual?.amount ?? null; const width = be && actual ? actual / be * 100 : 0; const { ref, hasEntered } = useInViewOnce<HTMLDivElement>(); return <div ref={ref} className={`${styles.chartStage} ${hasEntered ? styles.chartRevealed : ''}`}><div className={styles.chartTitle}><span>{view.name}</span><span className={styles.chartStatus}>{t('PLAN / EXECUTION')}</span></div><div className={styles.instrument} aria-label={`${view.name}: ${t('annual Budget Estimate and provisional actual through June')}`}><div className={styles.instrumentRow}><div className={styles.instrumentLabel}><span className={styles.planKey} /><div><strong>{t('Budget Estimate')}</strong><small>{t('annual plan')}</small></div></div><div className={styles.instrumentTrack}><span className={styles.trackEnd} /><div className={styles.planLine} /></div><AnimatedCurrency value={be} /></div><div className={styles.instrumentRow}><div className={styles.instrumentLabel}><span className={styles.actualKey} /><div><strong>{t('Actual through June')}</strong><small>{t('cumulative · provisional')}</small></div></div><div className={styles.instrumentTrack}><span className={styles.trackEnd} /><div className={styles.actualLine} style={{ width: hasEntered ? `${width}%` : '0%' }}><i /></div><b className={styles.actualPoint} style={{ left: hasEntered ? `${width}%` : '0%' }} /></div><AnimatedCurrency value={actual} /></div></div><div className={styles.instrumentAxis}><span>{localizeFormattedValue('0')}</span><span>{t('100% of annual Budget Estimate')}</span></div><p className={styles.chartCaption}>{view.actual ? `${localizeFormattedValue(formatPercentage(view.rate?.value ?? 0))} ${t('of the annual Budget Estimate had been recorded through June.')}` : t('Actual data is unavailable for this metric.')}</p></div>; }
function CompareBar({ label, id, tone, onSource }: { label: string; id: MetricId; tone: 'warm' | 'cool'; onSource: (o: FinancialObservation | null) => void }) { const { t, localizeFormattedValue } = useTranslation(); const be = getBudgetEstimate(id); const actual = getLatestActual(id); const rate = getExecutionRate(id); return <div className={styles.compareRow}><div className={styles.compareLabel}><span className={tone === 'warm' ? styles.warmMark : styles.coolMark} /><div><strong>{label}</strong><small>{rate ? localizeFormattedValue(formatPercentage(rate.value)) : t('Data unavailable')} {t('through June')}</small></div></div><div className={styles.compareValues}><span><small>{t('BE')}</small>{be ? localizeFormattedValue(formatCurrency(be.amount)) : t('Data unavailable')}</span><span><small>{t('ACTUAL')}</small>{actual ? localizeFormattedValue(formatCurrency(actual.amount)) : t('Data unavailable')}</span><button onClick={() => onSource(actual ?? be)} aria-label={`${t('View source')} ${label}`}>↗</button></div><div className={styles.compareTrack}><i className={tone === 'warm' ? styles.warmBar : styles.coolBar} style={{ width: `${Math.min(rate?.value ?? 0, 100)}%` }} /></div></div>; }
function FlowLine({ label, id }: { label: string; id: MetricId }) { const { localizeFormattedValue } = useTranslation(); const value = getBudgetEstimate(id)?.amount ?? 0; const total = getBudgetEstimate('non_borrowed_receipts')?.amount ?? 1; const share = value / total * 100; return <div className={styles.flowLine}><span>{label}</span><strong>{localizeFormattedValue(`${share.toFixed(1)}%`)}</strong><small>{localizeFormattedValue(formatCurrency(value))}</small><i><b style={{ width: `${share}%` }} /></i></div>; }
function receiptShare(id: MetricId) { const value = getBudgetEstimate(id)?.amount ?? 0; const total = getBudgetEstimate('non_borrowed_receipts')?.amount ?? 1; return (value / total * 100).toFixed(1); }
function StatusPill() { const { t } = useTranslation(); return <div className={styles.statusPill}><span>{t('PROVISIONAL')}</span><b>{t('Actual data through June 2026')}</b><small>{t('Subject to audit by CAG')}</small></div>; }
function formatObservation(observation: FinancialObservation | null, t: (text: string) => string, localize: (text: string) => string) { return observation ? localize(formatCurrency(observation.amount)) : t('Data unavailable'); }
function Progression({ view, onSource }: { view: MetricView; onSource: (o: FinancialObservation | null) => void }) { const { t, localizeFormattedValue } = useTranslation(); const points = view.progression; const periodIndex: Record<string, number> = { apr: 0, 'apr-may': 1, 'apr-jun': 2 }; const months = ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar']; return <div className={styles.progression}><div className={styles.progressionHead}><span>{t('YTD progression')}</span><button onClick={() => onSource(view.actual ?? view.be)}>{t('Source ↗')}</button></div>{points.length ? <div className={styles.progressionTrace} role="img" aria-label={`${view.name} ${t('cumulative progression')}: ${points.map(p => `${t(p.period ? (PERIOD_LABELS[p.period] ?? p.period) : 'Period unavailable')}: ${localizeFormattedValue(formatCurrency(p.amount))}`).join(', ')}. ${t('July through March are not available.')}`}><div className={styles.progressionLine}><i style={{ width: `${((periodIndex[points[points.length - 1]?.period ?? 'apr-jun'] ?? 2) / 11) * 100}%` }} /></div>{months.map((month, index) => { const point = points.find(p => periodIndex[p.period ?? ''] === index); return <div className={`${styles.progressionPoint} ${point ? styles.progressionPointComplete : styles.progressionPointFuture}`} key={month}><b>{point ? '●' : '○'}</b><strong>{t(month)}</strong>{point && <span>{localizeFormattedValue(formatCurrency(point.amount))}</span>}</div>; })}</div> : <p>{t('Progression unavailable for this metric.')}</p>}<small>{t('Each point is cumulative YTD; no monthly flow has been inferred. Future periods are not available.')}</small></div>; }
function EvidenceTrace({ observation }: { observation: FinancialObservation }) {
  const { t, localizeFormattedValue } = useTranslation();
  const isDerived = observation.source.dataStatus === 'derived';
  const stages = [
    { label: t('Official source'), detail: observation.source.organization },
    { label: t('Raw record preserved'), detail: observation.source.document },
    { label: t('Normalized observation'), detail: t('Canonical metric · ₹ crore') },
    ...(isDerived ? [{ label: t('Derived calculation'), detail: observation.source.table ?? t('Calculated from source observations') }] : []),
    { label: t('Displayed value'), detail: localizeFormattedValue(formatCurrency(observation.amount, { forceUnit: 'crore' })) },
  ];

  return <div className={styles.evidenceTrace}>{stages.map((stage, index) => <div key={stage.label} className={styles.evidenceStage}><b>{String(index + 1).padStart(2, '0')}</b><span>{stage.label}</span><small>{stage.detail}</small>{index < stages.length - 1 && <i aria-hidden="true" />}</div>)}</div>;
}
function ProvenanceDrawer({ observation, onClose }: { observation: FinancialObservation; onClose: () => void }) { const { t, localizeMetric } = useTranslation(); const provenance = getMetricProvenance(observation); const rawDefinition = getMetricDefinition(observation.metric); const def = rawDefinition ? localizeMetric(rawDefinition) : null; const isDerived = observation.source.dataStatus === 'derived'; return <div className={styles.drawerBackdrop} onClick={onClose}><aside className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="provenance-title" onClick={e => e.stopPropagation()}><button className={styles.closeButton} onClick={onClose} aria-label={t('Close source details')}>×</button><p className={styles.kicker}>{t('Provenance')}</p><h2 id="provenance-title">{def?.displayName ?? observation.metric}</h2><div className={styles.provenanceStatus}>{t(isDerived ? 'ARTHREKHA-DERIVED' : observation.estimateType === 'BE' ? 'BUDGET ESTIMATE' : 'PROVISIONAL ACTUAL')}<span>{t(observation.estimateType === 'BE' ? 'Annual plan' : 'Cumulative through June 2026')}</span></div><dl>{provenance && <><dt>{t('Jurisdiction')}</dt><dd>{t('Union Government of India')}</dd><dt>{t('Financial year')}</dt><dd>{t('FY')} {observation.financialYear}</dd><dt>{t('Period')}</dt><dd>{t(observation.estimateType === 'BE' ? 'Full year' : 'April–June 2026 (YTD)')}</dd><dt>{t('Source organization')}</dt><dd>{provenance.source.organization}</dd><dt>{t('Source document')}</dt><dd>{provenance.source.document}</dd><dt>{t('Published')}</dt><dd>{provenance.source.publishedAt ?? t('Not available')}</dd><dt>{t('Retrieved')}</dt><dd>{provenance.source.retrievedAt}</dd><dt>{t('Data status')}</dt><dd>{t(isDerived ? 'Derived from official source values' : provenance.source.dataStatus === 'provisional' ? 'Provisional / unaudited' : 'Final Budget Estimate')}</dd></>}</dl><EvidenceTrace observation={observation} /><p className={styles.drawerNote}>{t(isDerived ? 'This displayed observation is an Arthrekha calculation based on the official source values shown above.' : 'This displayed amount comes directly from the normalized source observation.')} {t('Execution rates, where available, are calculated separately as Actual YTD ÷ Budget Estimate × 100.')}</p>{provenance?.source.url && <a href={provenance.source.url} target="_blank" rel="noreferrer">{t('Open source publication ↗')}</a>}</aside></div>; }
